export const ADD_USER = 'ADD_USER';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const ADD_REPLY_MESSAGE = 'ADD_REPLY_MESSAGE';
export const RECEIVE_REPLY_MESSAGE = 'RECEIVE_REPLY_MESSAGE';
export const SEND_USERS = 'SEND_USERS';
